### ISSUE TITLE
Inclusion of entire flutter-desktop-embedding repository should not be necessary

### ISSUE THREAD

**Issue by stuartmorgan** [AppleEducate/flutter_everywhere#1]
Your README says:

> For now it [...] has to be nested inside flutter-desktop-embedding.

I'm curious why this is the case, given that the `macos`/`windows`/`linux` folders no longer have dependencies on the rest of FDE, and should be fully relocatable.

**Comment by AppleEducate** [comment]
Yesterday it did, at the time I was using it, but I will update accordingly!

**Comment by stuartmorgan** [comment]
It was already true of the version you have duplicated into your repository (see your copy of Quick-Start.md, which already has the updated instructions, for instance), which is why I'm wondering what issues you saw that caused you to conclude that it was still necessary.

**Comment by AppleEducate** [comment]
When I was running it on macOS it was throwing an error for the precompiled header looking for ‘flutter-desktop-embedding’. 

Could have been something I didn’t or did do though.
