### ISSUE TITLE
Version matching strategy?

### ISSUE THREAD

**Issue by stuartmorgan** [AppleEducate/flutter_everywhere#2]
As documented in the flutter-desktop-embedding project READMEs, the interface between the Flutter tools/libraries and the platform code in `macos`/`windows`/`linux` is highly unstable, and can break at any time. Changes are made to both sides at approximately the same time, so the expectation is that if you update both FDE and Flutter at the same time you should get a working build; any other combination may well not work.

Per your README:
> The goal of this repo is to have everything you need to start with flutter desktop + mobile simply by forking the project. 

Since you are adding a layer of indirection where you have to update your project from FDE for users of this repo to get updates for this to work reliably (unless you mirror FDE updates into your project in near-real-time) someone syncing your project needs to sync the version of Flutter that was HEAD at the time you updated your project from FDE.

I recommend that you prominently document that limitation, and include the hash of Flutter that your latest sync from FDE is matched with in the README so that people know how to get a version that is likely to work.

**Comment by AppleEducate** [comment]
Absolutely, I’ll update the readme!

**Comment by AppleEducate** [comment]
I think this project will target the master branch and flutter version releases.

**Comment by stuartmorgan** [comment]
> I recommend that you prominently document that limitation, and include the hash of Flutter that your latest sync from FDE is matched with in the README so that people know how to get a version that is likely to work.

I see from project history that you've updated from FDE several times, but still aren't including this info in the readme. Given that I'm assuming that I misunderstood and this is intended primarily for your use, where knowing the necessary versions to match isn't an issue. Given that, closing.

**Comment by AppleEducate** [comment]
@stuartmorgan yes I am using it for all my stuff. I was trying to create releases that matched the Flutter version. 

I’ll update the documentation but right now I am personally using it and updating from the various sources and fixing any limitations. 

I target the master and dev branch of Flutter. 

I use this project to populate my examples and other Flutter apps that I need to support desktop.

I want to reduce the amount of boilerplate to get up and running.
